### ISSUE TITLE
Missing data?

### ISSUE THREAD

**Issue by AlexIzydorczyk** [anttsou/qmj#1]
Hi - this is a really useful package for exploration, thanks for making it!

However, I've been going through the readme and noticed that:

```
#And more detailed data sets into what makes up quality
data(profitability)
data(growth)
data(payouts)
data(safety)
```

does not seem to work. Is this data available?

Thanks,
Alex

**Comment by rynkwn** [comment]
Hey Alex,

Sorry for getting back to you so late! The profitability, growth, payouts, and safety data sets were removed some time ago, and regrettably our documentation is pretty behind since our attentions have been elsewhere in the package.

We'll be fixing this pretty shortly though.

**Comment by anttsou** [comment]
Hey Alex, 

I did not see this issue earlier. Sorry about that! The data has been moved to a package called qmjdata to avoid space issues with R CMD check. We are looking into that issue right now to allow the data to still be accessible without any extra hassle.

**Comment by anttsou** [comment]
Sorry I misread the question earlier. Those have indeed been removed. If these datasets seem very helpful, let us know and we can re-add them! This mainly was to remove some clutter in our package.
