### ISSUE TITLE
Worth Repeating explanation of Russell 3000 in Prices and Financials data documentation?

### ISSUE THREAD

**Issue by rynkwn** [anttsou/qmj#11]
This is from an earlier push to the qmjdata repo, but one of the larger changes I implemented was to replace the detailed descriptions of the Russell 3000 Index in the prices and financials data sets with the single sentence "For more information on the Russell 3000 Index and why it was chosen, please see {link to companies data set}"

I don't see the repeated description of the Russell 3000 Index to be critical to understanding the Prices/Financials data sets, aside from mentioning that it's the source for the chosen companies.

However, I'm having second thoughts at the idea of an individual needing to go to another "page" if they wanted to find out more about the Index.

Your thoughts?

**Comment by davidkane9** [comment]
No strong opinion.

Dave

**Comment by anttsou** [comment]
I think it would be nicer to have just the link.

**Comment by rynkwn** [comment]
Alright, I'll close this issue and leave the current documentation as is then
