### ISSUE TITLE
If statement in market_data

### ISSUE THREAD

**Issue by rynkwn** [anttsou/qmj#13]
Specifically this statement:

```
if(length(which(financials$TCSO < 0))) {
    stop("Negative TCSO exists.")
  }
```

Was in the midst of updating documentation, and I'm not quite sure I understand the stop message, or why TCSO is specifically chosen. Can someone explain it to me?

**Comment by anttsou** [comment]
This is just for a test case to make sure the total common shares outstanding is non-negative. Do you think we should keep this check? If not, we can remove it.

**Comment by rynkwn** [comment]
Ahhhh. I see. The check makes sense, but I think a full stop for a single instance might be too harsh, since the most likely cases in which this occurs would be:

1) We read in the data wrong. In which case there'll probably be a decent distribution of negative "TCSO"s in our financials data set.
2) A tiny handful of companies have the wrong data listed on Google Finance.

In the former, where we detect that X% of the companies have negative TCSO's, we could stop with the message "Negative TCSO's detected for at least X% of companies. Please re-update the financials data set."
In the latter, it might make more sense to either ignore those companies or to let the user explicitly know that "Company X appears to have bad data, ignoring."

I wouldn't rate this as a priority issue though. Since Google Finance is likely pretty reasonable for this selection of companies, and in the case of (1) occurring, a full stop would be warranted anyways.

I'd keep the issue open for the moment in case we ever want to go back to this, but I wouldn't be too heartbroken if it's closed.

**Comment by rynkwn** [comment]
Actually, I'll close it. I think it's fine. If we ever want to change it in the future, we have that option.
