### ISSUE TITLE
README markdown file for github repo is badly, badly out of date

### ISSUE THREAD

**Issue by rynkwn** [anttsou/qmj#6]
Some data sets no longer exist. Have not yet checked function statuses.

**Comment by anttsou** [comment]
Got rid of the deprecated functions. Some additions may be needed to make it nicer, but should be accurate at the very least.

**Comment by rynkwn** [comment]
Looks to be accurate. My impression is that the package's been shaved down to just data gathering and producing quality scores. Am I right?

**Comment by davidkane9** [comment]
Yes

**Comment by rynkwn** [comment]
The readme seems functionally fine then. I suppose future edits might change the phrasing here and there, but I think this issue is essentially solved.
